### ISSUE TITLE
Add envFrom to values.yaml

### ISSUE THREAD

**Issue by beasteers** [digitalist-se/directus-helm-chart#55]
I'm using Flux to deploy this helm chart and I'm trying to factor out environment-specific values (in this case, oauth url).

Kustomize patches replace lists so you can't append environment variables from an overlay afaik. By putting them in a configmap, overlaying them would be trivial.

Here's an illustration.

Base layer:
```yaml
    extraEnvVars: #{}
      - name: CORS_ENABLED
        value: "true"
      - name: CORS_ORIGIN
        value: "true"
      - name: WEBSOCKETS_ENABLED
        value: 'true'
      - name: ADMIN_EMAIL
        valueFrom:
          secretKeyRef:
            name: admin-secret
            key: ADMIN_EMAIL
      - name: ADMIN_PASSWORD
        valueFrom:
          secretKeyRef:
            name: admin-secret
            key: ADMIN_PASSWORD
    ...
      - name: AUTH_PROVIDERS
        value: keycloak
      - name: AUTH_KEYCLOAK_DRIVER
        value: openid
      - name: AUTH_KEYCLOAK_IDENTIFIER_KEY
        value: email
      - name: AUTH_KEYCLOAK_ALLOW_PUBLIC_REGISTRATION
        value: "true"
      - name: AUTH_KEYCLOAK_CLIENT_ID
        value: directus
```

then in my `domains.yaml` overlay
```yaml
    extraEnvVars:
      - name: AUTH_KEYCLOAK_ISSUER_URL
        value: "https://auth.blah.blah/realms/blah/.well-known/openid-configuration"
```
which replaces all of the base environment variables. I'm really hoping to avoid having all of this in my domains file 😅
